"""Initial migration - User and TokenLLM tables

Revision ID: 54be4477c094
Revises: 
Create Date: 2025-10-29 13:48:44.959797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54be4477c094'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'token_llm',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_index(op.f('ix_token_llm_user_id'), 'token_llm', ['user_id'], unique=False)
    # op.drop_table('traffic_data')  # DB mới không có bảng này, bỏ đi
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('road_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('motor_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('car_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('motor_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('car_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recorded_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('recorded_time', postgresql.TIME(), server_default=sa.text('CURRENT_TIME'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('traffic_data_pkey'))
    )
    op.drop_index(op.f('ix_token_llm_user_id'), table_name='token_llm')
    op.drop_table('token_llm')
    # ### end Alembic commands ###
